{% set name = "channels" %}
{% set version = "3.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a3dc3339cc033e7c2afe083fb3dedf74fc5009815967e317e080e7bfdc92ea26

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - asgiref >=3.2.10,<4
    - daphne >=3.0,<4
    - django >=2.2
    - python >=3.5

test:
  imports:
    - channels
    - channels.generic
    - channels.management
    - channels.management.commands
    - channels.security
    - channels.testing

about:
  home: http://github.com/django/channels
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Brings async, event-driven capabilities to Django. Django 2.2 and up only.
  doc_url: https://channels.readthedocs.io
  dev_url: http://github.com/django/channels

extra:
  recipe-maintainers:
    - chrisbarber
